apiVersion:  argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
   name: cluster-generator
   namespace: argocd 
spec:
  generators:
  - clusters: {}
  template:
     metadata: 
         name: '{{name}}-application'
     spec:
        project: default
        destination:
             server: '{{server}}'
             namespace: default 
        source:
            repoURL: https://github.com/ROHITkumaw/multiargocluster.git
            path: ./
            targetRevision: main