apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argoapplistgen
spec:
  generators:
  - list:
      elements:
      - cluster: prodlistgenerator
        url: https://kubernetes.default.svc
      - cluster: staginglistgenerator
        url: https://192.168.59.113:8443
  template:
    metadata:
      name: '{{cluster}}-application'
    spec:
      project: default
      source:
        repoURL: https://github.com/infra-team/cluster-deployments.git
        targetRevision: HEAD
        path: multicluster/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: default
